export const dashboardSkeletonStyles = {
  root: "min-h-screen",
  main: "mx-auto max-w-[1540px] px-4 py-5 sm:px-8 sm:py-8",
  briefingHeader:
    "mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between",
  briefingIntro: "flex items-center gap-2.5",
  greeting: "h-6 w-32",
  date: "h-4 w-28",
  actions: "flex gap-3",
  primaryAction: "h-12 w-36",
  secondaryAction: "h-12 w-24",
  featureGrid: "grid items-stretch gap-4 lg:grid-cols-3",
  featureCard: "space-y-4 p-4 sm:p-5",
  cardHeader: "flex items-center gap-2.5",
  cardIcon: "size-9 shrink-0 rounded-full",
  cardTitle: "h-6 w-24",
  cardAction: "ml-auto h-5 w-20",
  cardMetric: "h-8 w-28",
  cardRows: "grid grid-cols-3 gap-2",
  cardRow: "h-12 w-full",
  secondaryGrid:
    "mt-5 grid gap-5 xl:grid-cols-[minmax(0,2.05fr)_minmax(330px,0.95fr)]",
  priorityCard: "space-y-3 p-7",
  priorityTitle: "mb-5 h-7 w-64",
  priorityRow: "h-16 w-full",
  scheduleCard: "space-y-4 p-7",
  scheduleTitle: "h-7 w-32",
  scheduleRow: "h-14 w-full",
  newsCard: "mt-5 space-y-5 p-5 sm:p-7",
  newsTitle: "h-7 w-64 max-w-full",
  newsGrid: "grid gap-4 md:grid-cols-3",
  newsItem: "h-28 w-full",
} as const;
